#!/bin/sh
# Make sure deps are available and run a Cardboard command.

set -e

cd $(dirname "$0")/..

BUNDLE=.bundle
BIN=$BUNDLE/binstubs
CARDBOARD=$BIN/cardboard
SCRIPT=$(basename "$0")

rm -rf {$BIN,$BUNDLE/config}
bundle install --binstubs "$BIN" --path "$BUNDLE" --quiet
"$CARDBOARD" bootstrap

exec "$CARDBOARD" "$SCRIPT" "$@"
